INSERT INTO ativo (cod_ativo,desc_ativo,id_tipo_ativo) VALUES
	 ('ITSA4','ITAUSA S/A',2),
	 ('BCFF11','FII BTG PACTUAL FUNDO DE FUNDOS',1),
	 ('BCFF13','FII BTG PACTUAL FUNDO DE FUNDOS',1),
	 ('BCFF14','FII BTG PACTUAL FUNDO DE FUNDOS',1),
	 ('BTLG11','BTG PACTUAL LOGISTICA',1),
	 ('BTLG13','BTG PACTUAL LOGISTICA',1),
	 ('KNCR11','KINEA RENDIMENTOS IMOBILIARIOS',1),
	 ('HGBS11','HEDGE BRASIL SHOPPING',1),
	 ('HGLG11','CSHG LOGISTICA',1),
	 ('HGRE11','CSHG REAL ESTATE',1);
INSERT INTO ativo (cod_ativo,desc_ativo,id_tipo_ativo) VALUES
	 ('KNRI11','KINEA RENDA IMOBILIÁRIA',1),
	 ('MXRF11','MAXI RENDA',1),
	 ('MXRF13','MAXI RENDA',1),
	 ('MXRF15','MAXI RENDA',1),
	 ('PETR4','PETROLEO BRASILEIRO',2),
	 ('VILG11','FII VINCILOG',1),
	 ('VILG13','FII VINCILOG',1),
	 ('VILG14','FII VINCILOG',1),
	 ('VISC11','VINCI SHOPPING',1),
	 ('XPLG11','XP LOG',1);
INSERT INTO ativo (cod_ativo,desc_ativo,id_tipo_ativo) VALUES
	 ('XPLG13','XP LOG',1),
	 ('XPLG14','XP LOG',1),
	 ('MXRF14','MAXI RENDA',1),
	 ('VILG15','FII VINCILOG',1),
	 ('HGLG14','CSHG LOGISTICA',1);
